import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  // 검색바
  searchBar: {
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 0.5,
    borderColor: "#E0F0EA",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 12,
    color: "#333",
  },
  searchBtn: {
    backgroundColor: "#1D9E75",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  searchBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
  },
  // 퍼센테이지 바
  pctRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  pctLabel: {
    fontSize: 12,
    color: "#333",
    fontWeight: "500",
    minWidth: 58,
  },
  pctTrack: {
    flex: 1,
    backgroundColor: "#E0F0EA",
    borderRadius: 4,
    height: 7,
  },
  pctFill: {
    backgroundColor: "#1D9E75",
    borderRadius: 4,
    height: 7,
  },
  pctValue: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1D9E75",
    minWidth: 32,
    textAlign: "right",
  },
  pctInfoBtn: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#1D9E75",
    alignItems: "center",
    justifyContent: "center",
  },
  pctInfoBtnText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1D9E75",
  },
  // 지도 영역
  mapArea: {
    borderRadius: 16,
    overflow: "hidden",
    height: 200,
    borderWidth: 0.5,
    borderColor: "#C8EDE0",
    marginBottom: 10,
    position: "relative",
  },
  mapBg: {
    flex: 1,
    backgroundColor: "#ddeee7",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  mapBgText: {
    fontSize: 12,
    color: "#0F6E56",
    fontWeight: "500",
  },
  mapPin: {
    position: "absolute",
    top: "45%",
    left: "55%",
    alignItems: "center",
  },
  mapPinLabel: {
    backgroundColor: "#fff",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    fontSize: 10,
    color: "#111",
    fontWeight: "600",
    marginTop: 2,
  },
  mapFilterChips: {
    position: "absolute",
    top: 10,
    left: 10,
    flexDirection: "row",
    gap: 6,
  },
  mapChip: {
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 5,
  },
  mapChipActive: {
    backgroundColor: "#1D9E75",
  },
  mapChipText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#2D7A5A",
  },
  mapChipTextActive: {
    color: "#fff",
  },
  // 병원 리스트
  hospListTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#222",
    marginBottom: 8,
    paddingLeft: 2,
  },
  hospListCard: {
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 0.5,
    borderColor: "#EAF6F1",
    padding: 14,
    marginBottom: 10,
    gap: 5,
  },
  hospListTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  hospOpenBadge: {
    backgroundColor: "#EAF6F1",
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 20,
  },
  hospOpenBadgeText: {
    fontSize: 10,
    color: "#1D9E75",
    fontWeight: "600",
  },
  hospListName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111",
  },
  hospListMeta: {
    fontSize: 11,
    color: "#9DB8B0",
  },
  hospListBtns: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  hospListBtnReserve: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: "#1D9E75",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  hospListBtnReserveText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
  },
  hospListBtnNav: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 0.5,
    borderColor: "#ddd",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  hospListBtnNavText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#333",
  },
  // 플로팅 패널
  floatingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.25)",
    zIndex: 10,
  },
  floatingPanel: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    paddingBottom: 24,
    zIndex: 20,
  },
  floatingHandle: {
    width: 36,
    height: 4,
    backgroundColor: "#E0EDE8",
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: 14,
  },
  floatingTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  floatingHospName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111",
    marginBottom: 5,
  },
  floatingHospInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 3,
  },
  floatingHospInfoText: {
    fontSize: 11,
    color: "#9DB8B0",
  },
  floatingCloseBtn: {
    backgroundColor: "#F5F5F5",
    borderRadius: 15,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  floatingCloseBtnText: {
    fontSize: 15,
    color: "#333",
  },
  floatingRating: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 14,
  },
  floatingRatingScore: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1D9E75",
  },
  floatingRatingDist: {
    fontSize: 12,
    color: "#aaa",
  },
  floatingBtns: {
    flexDirection: "row",
    gap: 8,
  },
  floatingBtnReserve: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 24,
    backgroundColor: "#1D9E75",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  floatingBtnReserveText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#fff",
  },
  floatingBtnNav: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 0.5,
    borderColor: "#ddd",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  floatingBtnNavText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#333",
  },
});
