import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  // 사후 관리 카드
  fitbingCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 0.5,
    borderColor: "#EAF6F1",
    marginBottom: 10,
  },
  fitbingHeader: {
    backgroundColor: "#5DCAA5",
    padding: 16,
    paddingBottom: 20,
  },
  fitbingHeaderSub: {
    fontSize: 12,
    color: "#fff",
    opacity: 0.88,
    marginBottom: 4,
  },
  fitbingHeaderTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
  },
  fitbingInputArea: {
    padding: 16,
    gap: 14,
  },
  fitbingLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 8,
  },
  fitbingLabelText: {
    fontSize: 11,
    color: "#9DB8B0",
  },
  fitbingUploadBtn: {
    borderWidth: 1.5,
    borderColor: "#4DC9A0",
    borderStyle: "dashed",
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#F5FBF8",
  },
  fitbingUploadBtnText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#1D9E75",
  },
  fitbingTextarea: {
    borderWidth: 1,
    borderColor: "#E0F0EA",
    borderRadius: 10,
    padding: 10,
    fontSize: 12,
    color: "#333",
    backgroundColor: "#FAFDFB",
    height: 100,
    textAlignVertical: "top",
  },
  fitbingDiagnoseBtn: {
    backgroundColor: "#5DCAA5",
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  fitbingDiagnoseBtnDisabled: {
    backgroundColor: "#A8DCC9",
  },
  fitbingDiagnoseBtnText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
  },
  fitbingDisclaimer: {
    fontSize: 10,
    color: "#B0C8C0",
    textAlign: "center",
    marginTop: -6,
  },
  // 결과 영역
  fitbingResultArea: {
    gap: 12,
  },
  fitbingResultCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 0.5,
    borderColor: "#EAF6F1",
    gap: 12,
    marginBottom: 10,
  },
  fitbingResultHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fitbingResultTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  fitbingResultTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1D9E75",
    marginLeft: 5,
  },
  fitbingResultBadge: {
    backgroundColor: "#EAF6F1",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  fitbingResultBadgeText: {
    fontSize: 10,
    color: "#1D9E75",
    fontWeight: "500",
  },
  fitbingDiseaseRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fitbingDiseaseName: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111",
  },
  fitbingDiseaseSub: {
    fontSize: 11,
    color: "#aaa",
    marginTop: 3,
  },
  fitbingCircle: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 3,
    borderColor: "#1D9E75",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5FBF8",
  },
  fitbingCircleText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1D9E75",
  },
  fitbingAdvice: {
    backgroundColor: "#F0FAF5",
    borderRadius: 10,
    padding: 11,
    borderWidth: 0.5,
    borderColor: "#C8EDE0",
  },
  fitbingAdviceText: {
    fontSize: 12,
    color: "#2D7A5A",
    lineHeight: 18,
  },
  fitbingLegal: {
    fontSize: 10,
    color: "#B0C8C0",
    textAlign: "center",
  },
  // 복약 알림 설정
  alarmCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 0.5,
    borderColor: "#EAF6F1",
    gap: 14,
    marginBottom: 10,
  },
  alarmTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  alarmTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#222",
    marginLeft: 5,
  },
  alarmSubtitle: {
    fontSize: 11,
    color: "#9DB8B0",
    marginTop: 3,
  },
  dosageBtns: {
    flexDirection: "row",
    gap: 8,
  },
  dosageBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#F5F5F5",
    alignItems: "center",
  },
  dosageBtnActive: {
    backgroundColor: "#1D9E75",
  },
  dosageBtnText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#888",
  },
  dosageBtnTextActive: {
    color: "#fff",
  },
  pushLabel: {
    fontSize: 12,
    color: "#9DB8B0",
    marginBottom: 10,
  },
  alarmItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  alarmItemTitle: {
    fontSize: 13,
    fontWeight: "500",
    color: "#222",
    marginBottom: 2,
  },
  alarmItemSub: {
    fontSize: 11,
    color: "#9DB8B0",
  },
  toggle: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#ddd",
    justifyContent: "center",
    padding: 3,
  },
  toggleOn: {
    backgroundColor: "#1D9E75",
  },
  toggleThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#fff",
  },
  toggleThumbOn: {
    alignSelf: "flex-end",
  },
  // 가까운 병원
  nearbyCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 0.5,
    borderColor: "#EAF6F1",
    gap: 12,
    marginBottom: 10,
  },
  nearbyTitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  nearbyTitleText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#222",
    marginLeft: 5,
  },
  nearbyHospBox: {
    backgroundColor: "#F5FBF8",
    borderRadius: 12,
    padding: 12,
    borderWidth: 0.5,
    borderColor: "#C8EDE0",
    gap: 6,
  },
  nearbyHospTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  nearbyOpenBadge: {
    backgroundColor: "#EAF6F1",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 20,
  },
  nearbyOpenBadgeText: {
    fontSize: 10,
    color: "#1D9E75",
    fontWeight: "600",
  },
  nearbyHospName: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111",
  },
  nearbyHospMeta: {
    fontSize: 11,
    color: "#9DB8B0",
  },
  nearbyBtns: {
    flexDirection: "row",
    gap: 8,
    marginTop: 4,
  },
  nearbyBtnReserve: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: "#1D9E75",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  nearbyBtnReserveText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
  },
  nearbyBtnNav: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: "#fff",
    borderWidth: 0.5,
    borderColor: "#ddd",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  nearbyBtnNavText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#333",
  },
  moreHospBtn: {
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: "#5DCAA5",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  moreHospBtnText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#fff",
  },
});
