import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5faf8" },

  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#f5faf8",
    borderBottomWidth: 1,
    borderBottomColor: "#e8f0ec",
  },
  backBtn: { padding: 4, width: 32 },
  headerTitle: { fontSize: 17, fontWeight: "700", color: "#111" },
  markAllBtn: { width: 64, alignItems: "flex-end" },
  markAllText: { fontSize: 13, color: "#5DCAA5", fontWeight: "600" },

  sectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#aaa",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 6,
  },

  card: {
    backgroundColor: "#fff",
    marginHorizontal: 12,
    marginBottom: 10,
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },

  cardTop: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  cardTitle: { flex: 1, fontSize: 13, fontWeight: "600", color: "#555" },
  cardTime: { fontSize: 11, color: "#bbb" },
  cardHeadline: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111",
    marginBottom: 6,
  },
  cardBody: { fontSize: 13, color: "#555", lineHeight: 19, marginBottom: 4 },
  cardLegal: { fontSize: 10, color: "#bbb", marginTop: 6 },

  actionRow: { flexDirection: "row", gap: 8, marginTop: 12 },
  actionBtnPrimary: {
    flex: 1,
    backgroundColor: "#5DCAA5",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  actionBtnSecondary: {
    flex: 1,
    backgroundColor: "#f0f0f0",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  actionBtnDanger: {
    flex: 1,
    backgroundColor: "#FFB3B3",
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
  },
  actionBtnTextPrimary: { fontSize: 14, fontWeight: "700", color: "#fff" },
  actionBtnTextSecondary: { fontSize: 14, fontWeight: "600", color: "#888" },
  actionBtnTextDanger: { fontSize: 14, fontWeight: "700", color: "#fff" },

  hospBox: {
    backgroundColor: "#f5faf8",
    borderRadius: 12,
    padding: 12,
    marginTop: 10,
  },
  hospTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  hospBadgeRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  hospRecommendBadge: {
    backgroundColor: "#edf9f4",
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  hospRecommendBadgeText: { fontSize: 10, color: "#5DCAA5", fontWeight: "700" },
  hospOpenBadge: {
    backgroundColor: "#edf9f4",
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  hospOpenBadgeText: { fontSize: 10, color: "#5DCAA5", fontWeight: "700" },
  hospRating: { fontSize: 13, color: "#555", fontWeight: "600" },
  hospName: { fontSize: 15, fontWeight: "700", color: "#111", marginBottom: 2 },
  hospMeta: { fontSize: 12, color: "#888", marginBottom: 10 },
  hospBtnRow: { flexDirection: "row", gap: 8 },
  hospBtnReserve: {
    flex: 1,
    backgroundColor: "#5DCAA5",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
  },
  hospBtnReserveText: { fontSize: 13, fontWeight: "700", color: "#fff" },
  hospBtnNav: {
    flex: 1,
    backgroundColor: "#f0f0f0",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
  },
  hospBtnNavText: { fontSize: 13, fontWeight: "600", color: "#333" },

  aiBadge: {
    backgroundColor: "#edf9f4",
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  aiBadgeText: { fontSize: 11, color: "#5DCAA5", fontWeight: "700" },
  aiRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  aiDiseaseName: { fontSize: 18, fontWeight: "700", color: "#111" },
  aiDiseaseSub: { fontSize: 12, color: "#888", marginTop: 2 },
  aiCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#edf9f4",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2.5,
    borderColor: "#5DCAA5",
  },
  aiCircleText: { fontSize: 15, fontWeight: "800", color: "#5DCAA5" },
  aiAdvice: {
    backgroundColor: "#f5faf8",
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  aiAdviceText: { fontSize: 12, color: "#555", lineHeight: 18 },
  aiLegal: { fontSize: 10, color: "#bbb", textAlign: "center", lineHeight: 16 },

  subLabel: { fontSize: 12, color: "#888", marginBottom: 8 },
  mealRow: { flexDirection: "row", gap: 6, marginBottom: 8 },
  mealChip: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#5DCAA5",
    alignItems: "center",
  },
  mealChipInactive: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#f0f0f0",
    alignItems: "center",
  },
  mealChipText: { fontSize: 13, fontWeight: "600", color: "#fff" },
  mealChipTextInactive: { fontSize: 13, fontWeight: "600", color: "#aaa" },
  dosageRow: { flexDirection: "row", gap: 6, marginBottom: 14 },
  dosageChip: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "#f0f0f0",
    alignItems: "center",
  },
  dosageChipActive: { backgroundColor: "#5DCAA5" },
  dosageChipText: { fontSize: 13, fontWeight: "600", color: "#aaa" },
  dosageChipTextActive: { color: "#fff" },

  pushLabel: {
    fontSize: 12,
    color: "#aaa",
    fontWeight: "600",
    marginBottom: 4,
  },
  toggleItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 11,
    borderTopWidth: 1,
    borderTopColor: "#f5f5f5",
  },
  toggleItemTitle: { fontSize: 13, fontWeight: "600", color: "#222" },
  toggleItemSub: { fontSize: 11, color: "#bbb", marginTop: 2 },
  toggle: {
    width: 44,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#ddd",
    justifyContent: "center",
    paddingHorizontal: 2,
  },
  toggleOn: { backgroundColor: "#5DCAA5" },
  toggleThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  toggleThumbOn: { alignSelf: "flex-end" },

  moreBtnWrap: { marginHorizontal: 12, marginBottom: 10 },
  moreBtn: {
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  moreBtnText: { fontSize: 14, fontWeight: "600", color: "#5DCAA5" },
});
